flags:
  second-transfer:
    debug: false
docker:
    enable: false
packages:
- '.'
flags:
    second-transfer: 
        fastc: true
ghc-options:
    second-transfer: "-pgmc g++"
resolver: nightly-2015-10-13
