flags:
  second-transfer:
    debug: false
docker:
    enable: false
packages:
- '.'
- examples/attempt_bust
resolver: lts-3.7
flags:
    second-transfer: 
        fastc: true
ghc-options:
    second-transfer: "-pgmc g++"
